const TOPIC_TAGS = [
    { name: 'Array', slug: 'array', count: 1934 },
    { name: 'String', slug: 'string', count: 797 },
    { name: 'Hash Table', slug: 'hash-table', count: 707 },
    { name: 'Dynamic Programming', slug: 'dynamic-programming', count: 597 },
    { name: 'Math', slug: 'math', count: 588 },
    { name: 'Sorting', slug: 'sorting', count: 457 },
    { name: 'Greedy', slug: 'greedy', count: 419 },
    { name: 'Depth-First Search', slug: 'depth-first-search', count: 326 },
    { name: 'Binary Search', slug: 'binary-search', count: 309 },
    { name: 'Database', slug: 'database', count: 308 },
    { name: 'Matrix', slug: 'matrix', count: 260 },
    { name: 'Tree', slug: 'tree', count: 250 },
    { name: 'Breadth-First Search', slug: 'breadth-first-search', count: 245 },
    { name: 'Bit Manipulation', slug: 'bit-manipulation', count: 243 },
    { name: 'Two Pointers', slug: 'two-pointers', count: 220 },
    { name: 'Prefix Sum', slug: 'prefix-sum', count: 206 },
    { name: 'Heap (Priority Queue)', slug: 'heap', count: 195 },
    { name: 'Simulation', slug: 'simulation', count: 182 },
    { name: 'Binary Tree', slug: 'binary-tree', count: 177 },
    { name: 'Stack', slug: 'stack', count: 171 },
    { name: 'Graph', slug: 'graph', count: 166 },
    { name: 'Counting', slug: 'counting', count: 164 },
    { name: 'Sliding Window', slug: 'sliding-window', count: 152 },
    { name: 'Design', slug: 'design', count: 130 },
    { name: 'Enumeration', slug: 'enumeration', count: 120 },
    { name: 'Backtracking', slug: 'backtracking', count: 108 },
    { name: 'Union Find', slug: 'union-find', count: 88 },
    { name: 'Linked List', slug: 'linked-list', count: 81 },
    { name: 'Number Theory', slug: 'number-theory', count: 72 },
    { name: 'Ordered Set', slug: 'ordered-set', count: 71 },
    { name: 'Monotonic Stack', slug: 'monotonic-stack', count: 68 },
    { name: 'Segment Tree', slug: 'segment-tree', count: 64 },
    { name: 'Trie', slug: 'trie', count: 57 },
    { name: 'Combinatorics', slug: 'combinatorics', count: 55 },
    { name: 'Bitmask', slug: 'bitmask', count: 53 },
    { name: 'Queue', slug: 'queue', count: 49 },
    { name: 'Recursion', slug: 'recursion', count: 49 },
    { name: 'Divide and Conquer', slug: 'divide-and-conquer', count: 48 },
    { name: 'Binary Indexed Tree', slug: 'binary-indexed-tree', count: 43 },
    { name: 'Memoization', slug: 'memoization', count: 42 },
    { name: 'Hash Function', slug: 'hash-function', count: 40 },
    { name: 'Geometry', slug: 'geometry', count: 40 },
    { name: 'Binary Search Tree', slug: 'binary-search-tree', count: 40 },
];
export default TOPIC_TAGS;